name: oyster-app
region: nyc

services:
  - name: pricing-simple
    source_dir: project_finance3/budget_projects

    github:
      repo: Vitaliy77/pricing-simple
      branch: main
      deploy_on_push: true

    environment_slug: node-js
    instance_count: 1
    http_port: 3000

    build_command: npm ci && npm run build
    output_dir: dist
    run_command: npx serve dist -s -l 3000

    routes:
      - path: /
