name: clownfish-app
region: nyc

services:
  - name: pricing-simple
    source_dir: project_finance3/budget_projects

    github:
      repo: Vitaliy77/pricing-simple
      branch: main
      deploy_on_push: true

    build_command: npm install && npm run build
    output_dir: dist

    # static site doesn't actually use run_command / environment_slug,
    # so you can omit them here if you want to keep it simple
