# .do/app.yaml
name: clownfish-app
region: nyc

services:
  - name: pricing-simple
    source_dir: project_finance3/budget_projects

    github:
      repo: Vitaliy77/pricing-simple
      branch: main
      deploy_on_push: true

    build_command: npm ci && npm run build
    output_dir: dist

    # This line kills the appbuild-logs error forever
    logs:
      disable_build_logs: true
