name: clownfish-app
region: nyc

static_sites:
  - name: pricing-simple
    source_dir: project_finance3/budget_projects

    github:
      repo: Vitaliy77/pricing-simple
      branch: main
      deploy_on_push: true

    build_command: npm ci && npm run build
    output_dir: dist

    routes:
      - path: /
