# .do/app.yaml
name: clownfish-app

services:
  - name: pricing-simple
    source_dir: /project_finance3/budget_projects/     # keep exactly this
    github:
      repo: Vitaliy77/pricing-simple
      branch: main
      deploy_on_push: true

    build_command: npm install && npm run build
    output_dir: dist                 # THIS LINE IS WHAT FIXES EVERYTHING
    run_command: npx serve dist -s -l 3000     # or "npm run preview" if you have it

    http_port: 3000
    instance_count: 1
    routes:
      - path: /
