name: clownfish-app
region: nyc   # add this at the top if it's not already set

services:
  - name: pricing-simple
    source_dir: project_finance3/budget_projects   # <— relative path, no leading slash

    github:
      repo: Vitaliy77/pricing-simple
      branch: main
      deploy_on_push: true

    environment_slug: node-js
    build_command: npm ci && npm run build    # you can also use `npm install && npm run build`
    output_dir: dist
    run_command: npx serve dist -s -l 3000

    instance_count: 1
    http_port: 3000
    routes:
      - path: /

    envs:
      - key: NODE_VERSION
        scope: RUN_AND_BUILD_TIME
        value: "18"

    # ⛔ remove this block for now
    # logs:
    #   disable_build_logs: true
